theme = "hugo-now-ui"
baseurl = "http://poulsbolawnrangers.com/"
relativeurls = true
languageCode = "en-us"
title = "Poulsbo Lawn Rangers!"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
#publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about"
    pre = "<i class='now-ui-icons travel_info'></i>"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/contact"
    pre = "<i class='now-ui-icons ui-1_bell-53'></i>"
    weight = 1



[params]
    background = "/img/grass.jpeg"
    tint = "green"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website for people who need their lawns mowed in Poulsbo Woods and Meadows"
